- include: check_vars.yml tags=laclasse,laclasse:docs,check_vars

- name: Send notification message via Slack
  local_action:
    module: slack
    domain: "{{ laclasse_slack.host }}"
    token: "{{ laclasse_slack.token }}"
    msg: "3...2...1... docs version {{ laclasse_docs_version }} @ {{ inventory_hostname }} :rocket: "
    channel: "{{ laclasse_slack.channel }}"
  ignore_errors: true
  tags:
    - laclasse
    - laclasse:docs

- include: docs.yml tags=laclasse:docs,laclasse

- name: Send notification message via Slack
  local_action:
    module: slack
    domain: "{{ laclasse_slack.host }}"
    token: "{{ laclasse_slack.token }}"
    msg: "docs (version {{ git_tag.stdout }}) successfully deployed on {{ inventory_hostname }} :thumbsup:"
    channel: "{{ laclasse_slack.channel }}"
  ignore_errors: true
  tags:
    - laclasse
    - laclasse:docs
